# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: [black==25.1.0]
        log_file: .black.log
        stages: [pre-commit]

      - id: pylint
        name: pylint
        entry: "python lint.py --threshold 9 --path"
        language: python
        types: [python]
        additional_dependencies: [pylint==3.3.6]
        stages: [pre-commit]
